Remove 5min connection timeout when restoring
Financial-Times/mongo-hot-backup pull request #6
Opened 2017-07-18 14:03 UTC by efinlay24

The MongoDB database connection for the restore function had a 5 minute timeout, causing restores to fail with large collections that took more than 5mins to restore.

This PR removes the timeout.

2017-07-18 14:16 UTC, tosan88 approved these changes

2017-07-19 08:48 UTC, kghatton requested changes
I think it's worth adding a note in the readme that the restore has no timeout (and could therefore go on "forever" if there is some weird problem that doesn't quite break things).

2017-07-19 12:52 UTC, efinlay24 commented
Yup, good point. I'll add a note the readme.

2017-07-19 13:08 UTC, kghatton approved these changes

2017-07-19 13:10 UTC, merged